import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
const version = manifest.version;
if (version !== JSON.parse(fs.readFileSync('package.json', 'utf8')).version) throw new Error('Version mismatch');
const target = path.resolve('release', version), plugin = path.join(target, 'review-center');
fs.mkdirSync(plugin, { recursive: true });
for (const file of ['main.js', 'styles.css', 'manifest.json', 'THIRD_PARTY_NOTICES.txt']) fs.copyFileSync(file, path.join(plugin, file));
fs.copyFileSync('assets/priority-queue-2.7.0-source.zip', path.join(plugin, 'priority-queue-2.7.0-source.zip'));
fs.cpSync('docs', path.join(target, 'docs'), { recursive: true });
fs.copyFileSync('README.md', path.join(target, '使用说明.md'));
fs.copyFileSync(`docs/${version}-upgrade.md`, path.join(target, '升级说明.md'));
fs.copyFileSync(`docs/${version}-validation.md`, path.join(target, '验证记录.md'));
const zip = path.join(target, `review-center-${version}.zip`);
if (fs.existsSync(zip)) fs.unlinkSync(zip);
execFileSync('zip', ['-q', '-X', '-r', zip, 'review-center'], { cwd: target, env: { ...process.env, COPYFILE_DISABLE: '1' } });
const files = [zip, ...fs.readdirSync(plugin).sort().map(file => path.join(plugin, file))];
fs.writeFileSync(path.join(target, 'SHA256SUMS'), files.map(file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex') + '  ' + path.relative(target, file)).join('\n') + '\n');
console.log(zip);
